---
title: "Meet the Group"
listing:
  - id: pi
    include: 
      people_group: "pi"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    type: grid
    fields: [title, subtitle, image, education]
  - id: researcher
    include: 
      people_group: "researcher"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    sort: last
    type: grid
    fields: [title, subtitle, image, education]
  - id: postdoc
    include: 
      people_group: "postdoc"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    sort: last    
    type: grid
    fields: [title, subtitle, image, education]
  - id: phdstudent
    include: 
      people_group: "phdstudent"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    sort: last
    type: grid
    fields: [title, subtitle, image, education]
  - id: phdstudent-co
    include: 
      people_group: "phdstudent-co"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    sort: last
    type: grid
    fields: [title, subtitle, image, education]
  - id: alumni
    include: 
      people_group: "alumni"
    exclude:
      external: true
    template: ../_ejs/alumni-box.ejs
    sort: last
    type: grid
    fields: [title, subtitle, image, education, altsubtitle, alteducation]
page-layout: full
---


## Principal Investigator


::: {#pi}
:::


## PhD Students



::: {#phdstudent}
:::



## PhD Students (Co-Supervision)



::: {#phdstudent-co}
:::

## Alumni

### Visitors

- Nina Weng (PhD exchange student from DTU)
- Jakob Lønborg Christensen (PhD exchange student from DTU)

### Master students

- Carina Schmidt (Master thesis Tübingen)
- Martin Paulikat (Master thesis Tübingen)
- Simon Gutwein (Master thesis Tübingen)
- Amel Abdelraheem (Research exchange and master thesis Tübingen)
- Hannah Willms (Research Project Tübingen)
- Arthur Jacques (HiWi Tübingen)
- Bartłomiej Baranowski (HiWi Tübingen)
- Dustin Theobald (Master thesis Tübingen)
- Leonard Siegert (Master thesis Tübingen)
- Mehrin Azan (Research Project Tübingen)

### Medical students

- Stephan Wunderlich (Research project Tübingen)
- David Jakobs (Research project Tübingen)

